[phases.setup]
# nodejs package from nixPkgs usually includes npm.
# Using nodejs_20 for Node.js version 20.x.
# You can try just "nodejs" if version doesn't matter or if _20 isn't found.
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

# No [phases.start] section
